version: "2"
services:
  laravel:
    image: andreicon/laravel
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
      - DB_DATABASE=homestead
      - APP_KEY=base64:fWgoOBWO8Tcg4I2KtIugxaQ6mLtOYgTf/N0M4l2pCgc=
    ports:
      - 8086:8000
    depends_on:
      - mysql
    volumes:
      - ./laravel:/home/andrei/laravel
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306