version: "2"
services:
  laravel:
    image: andreicon/laravel
    environment:
      - DB_HOST=mysql
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306